### ISSUE TITLE
To-do items toward a minimum viable product

### ISSUE THREAD

**Issue by jpivarski** [jpivarski/ragged#8]
- [x] replace `assert False, "TODO"` with `raise NotImplementedError` (the mypy constraint no longer exists).
- [x] creation functions `arange` (from NumPy/CuPy)
- [x] creation functions `empty` (from NumPy/CuPy)
- [x] creation functions `eye` (from NumPy/CuPy)
- [x] creation functions `from_dlpack` (from NumPy/CuPy)
- [x] creation functions `full` (from NumPy/CuPy)
- [x] creation functions `linspace` (from NumPy/CuPy)
- [x] creation functions `ones` (from NumPy/CuPy)
- [x] creation functions `zeros` (from NumPy/CuPy)
- [x] data type functions `can_cast` (from NumPy)
- [x] data type functions `finfo` (from NumPy)
- [x] data type functions `iinfo` (from NumPy)
- [x] data type functions `result_type` (from NumPy)
- [x] data type functions `astype` (from Awkward)
- [x] creation functions `empty_like` (from Awkward)
- [x] creation functions `full_like` (from Awkward)
- [x] creation functions `ones_like` (from Awkward)
- [x] creation functions `zeros_like` (from Awkward)
- [x] manipulation functions `broadcast_arrays` (from Awkward)
- [x] manipulation functions `concat` (from Awkward)
- [x] searching functions `nonzero` and `where` (from Awkward; the 1-arg and 3-arg cases)
- [x] array object `__dlpack__` and `__dlpack_device__` (only for rectilinear arrays)
- [x] array object `__getitem__`
- [x] array object `__len__` (and declare it to be a `Sequence` or `Sized` or something)
- [x] array object `__setitem__`
- [x] array object `__iter__`
- [x] array object `__init__`'s `copy` argument should do a `deepcopy`
- [x] manipulation functions `expand_dims` (from a slice)
- [x] manipulation functions `squeeze` (from a slice)
- [x] indexing functions `take` (from a slice)

This would reduce our 51 TODOs down to 20 (by filling in 31).

**Comment by jpivarski** [comment]
Now

```bash
% fgrep -r 'NotImplementedError("TODO ' src | wc -l
33
```

The remaining 8 check-boxes should bring it down by 7, down to 26 TODOs. (The accounting changed when I converted assertions into `NotImplementedError`.)

**Comment by jpivarski** [comment]
Now

```bash
% fgrep -r 'NotImplementedError("TODO ' src | wc -l
23
```

Yes, I got rid of a few others along the way (arguments in `ragged.array` functions).

All the rest of the `NotImplementedError` TODOs are in issues. They'll be addressed one at a time, as needed.
